version: '3.8'

services:
  redis:
    image: redis:7.4
    container_name: redis-container
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data:
